### PR TITLE
Create 30-10-22 Microsoft.cpp

### PR DESCRIPTION
**Pull request by Sehaj-kahlon**
solution to problem 
Microsoft 30-10-22

### CODE REVIEW

**Comment by vanshavenger** [comment]
shouldn't it be a < b in the while loop as

**Comment by Sehaj-kahlon** [comment]
> shouldn't it be a < b in the while loop as
yes sir since  if a == b the same number will be added twice 
i will correct it

**Comment by vanshavenger** [comment]
still showing a <= b 
have you corrected it?

**Comment by Sehaj-kahlon** [comment]
int the 5th commit

**Comment by Sehaj-kahlon** [comment]
in the 5th commit

**Review by Manobal-Singh-Bagady — COMMENTED** [review]
Changes were approved and merged by @vanshavenger 👍

**Pull request merged**
